name: Export Dynamic Plugin Packages (Caller)
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: node-version to execute the export
        required: false
        type: choice
        default: '20.x'
        options:
          - '18.x'
          - '20.x'

      janus-cli-version:
        description: Version of the janus-idp/cli package.
        type: string
        required: false
        default: '^1.13.1'

      upload-project-on-error:
        description: Upload the complete project as a workflow artifact in case of error in order to troubleshoot.
        required: false
        type: boolean
        default: false

      plugins-repo:
        description: Target Community Plugins repository to export plugins from
        type: string
        required: false
        default: 'backstage/community-plugins'

      overlay-branch:
        description: Branch of the overlay structure (current branch by default).
        type: string
        required: false
        default: ''

  push:
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - 'releases/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  parent_export:
    uses: redhat-developer/rhdh-plugin-export-backstage-community-plugins/.github/workflows/export-dynamic.yaml@main
    with:
      node-version: ${{ github.event.inputs.node-version }}
      janus-cli-version: ${{ github.event.inputs.janus-cli-version }}
      plugins-repo: ${{ github.event.inputs.plugins-repo }}
      upload-project-on-error: ${{ github.event.inputs.upload-project-on-error == 'true' }}
      overlay-branch: ${{ github.event.inputs.overlay-branch }}

    permissions:
      contents: write